version: "2.4"
services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d graphs" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    mem_limit: 0.25GB
  dj:
    container_name: dj
    # build:
    #   context: ./dj
    #   dockerfile: Dockerfile
    image: phdmabuze/graph-visualization_dj
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000" 
    restart: unless-stopped
    mem_limit: 0.25GB
  react:
    container_name: react-visualize
    restart: unless-stopped
    # build:
    #   context: ./react-visualize
    #   dockerfile: Dockerfile
    image: phdmabuze/graph-visualization_react
    ports:
      - "3000:80"
    depends_on:
      - dj
