# Generated by Django 4.2.3 on 2023-07-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=60)),
                ('kingdom', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'animals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.IntegerField()),
                ('target', models.IntegerField()),
            ],
            options={
                'db_table': 'relations',
                'managed': False,
            },
        ),
    ]
